sequencing: "pe"

input_dir: "/path/to/input"
output_dir: "/path/to/output"

dockercontainer: "docker://jverwilt/totalrna:v0.5"
  
reference:
  fasta: "/resources/Homo_sapiens.GRCh38.109_spikes.fa"
  gtf: "/resources/Homo_sapiens.GRCh38.109_spikes.gtf"
  bed: "/resources/Homo_sapiens.GRCh38.109_spikes.bed"

index:
  star: "/resources/Homo_sapiens.GRCh38.109.star_index"

resources:
  star_mem_mb: 60000
